[package]
name = "mdbook-svgbob"
version = "0.2.0"
authors = ["Alex Koz. <a@koz.email>"]
description = "SvgBob mdbook preprocessor which swaps code-blocks with neat SVG."
homepage = "https://nest.pijul.com/fzzr/mdbook-svgbob"
repository = "https://github.com/fzzr-/mdbook-svgbob.git"
keywords = ["mdbook", "markdown", "ascii", "svg", "bob"]
categories = ["command-line-utilities", "text-processing", "visualization"]

edition = "2018"

readme = "README.md"
license-file = "LICENSE"
include = ["src/**/*", "Cargo.toml", "README.md"]

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
mdbook = "0.4"
svgbob = "0.4"
svg = "0.7"

clap = "2.33"
log = "0.4"
env_logger = "0.7"
semver = "0.9.0"

toml = "0.5"
serde = "1.0"
serde_json = "1.0"
pulldown-cmark = "0.7"
pulldown-cmark-to-cmark = "3.0"
